from BaseClasses import Location
import typing


class AdvData(typing.NamedTuple):
    id: typing.Optional[int]
    region: str


class UndertaleYellowAdvancement(Location):
    game: str = "Undertale Yellow"

advancement_table = {
    "Ruins: Lemonade Stand": AdvData(96500, "Ruins"),
    "Ruins: Candy Corn": AdvData(96501, "Ruins"),
    "Ruins: Pebble Pile": AdvData(96502, "Ruins"),
    "Ruins: Stray Feather": AdvData(96503, "Ruins"),
    "Ruins: Corn Dog": AdvData(96504, "Ruins"),
    "Ruins: Golden Pear": AdvData(96505, "Ruins"),
    "Ruins: Dalv's Fridge": AdvData(96506, "Ruins"),
    "Snowdin: Ice Pellets": AdvData(96507, "Snowdin"),
    "Snowdin: Mo Snowdin 1": AdvData(96508, "Snowdin"),
    "Snowdin: Mo Snowdin 2": AdvData(96509, "Snowdin"),
    "Snowdin: Mo Snowdin 3": AdvData(96510, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 1": AdvData(96511, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 2": AdvData(96512, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 3": AdvData(96513, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 4": AdvData(96514, "Snowdin"),
    "Snowdin: Favorite Song Fan": AdvData(96515, "Snowdin"),
    "Snowdin: Golden Coffee": AdvData(96516, "Snowdin"),
    "Snowdin: Coffee Trade": AdvData(96517, "Snowdin"),
    "Snowdin: Mitten Trade": AdvData(96518, "Snowdin"),
    "Snowdin: Map Trade": AdvData(96519, "Snowdin"),
    "Snowdin: Matches Trade": AdvData(96520, "Snowdin"),
    "Snowdin: Scarf Trade": AdvData(96521, "Snowdin"),
    "Snowdin: Coffee Bean Barrel": AdvData(96522, "Snowdin"),
    "Snowdin: Bench Pancakes": AdvData(96523, "Snowdin"),
    "Dunes West: Trail Mix Chest": AdvData(96524, "Dunes West"),
    "Dunes West: Packing Peanuts": AdvData(96525, "Dunes West"),
    "Dunes West: Mo Dunes 1": AdvData(96526, "Dunes West"),
    "Dunes West: Mo Dunes 2": AdvData(96527, "Dunes West"),
    "Dunes West: Mo Dunes 3": AdvData(96528, "Dunes West"),
    "Dunes West: Flint Pile": AdvData(96529, "Dunes West"),
    "Dunes West: Steel Buckle Cubby": AdvData(96530, "Dunes West"),
    "Dunes West: Pickaxe": AdvData(96531, "Dunes West"),
    "Dunes East: Safety Jacket Hanger": AdvData(96532, "Dunes East"),
    "Dunes East: Stale Fruitcake": AdvData(96533, "Dunes East"),
    "Dunes East: Gift Shop Mug": AdvData(96534, "Dunes East"),
    "Dunes East: Spider Bake Sale": AdvData(96535, "Dunes East"),
    "Dunes East: Pants Pocket Robbery": AdvData(96536, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 1": AdvData(96638, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 2": AdvData(96639, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 3": AdvData(96640, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 4": AdvData(96641, "Dunes East"),
    "Dunes East: Wishing Well Gold": AdvData(96824, "Dunes East"),
    "Wild East: Wild East Barrel": AdvData(96654, "Wild East"),
    "Wild East: Dunes Barkeep 1": AdvData(96537, "Wild East"),
    "Wild East: Dunes Barkeep 2": AdvData(96538, "Wild East"),
    "Wild East: Dunes Barkeep 3": AdvData(96539, "Wild East"),
    "Wild East: Dunes Barkeep 4": AdvData(96540, "Wild East"),
    "Wild East: Dunes Gunsmith 1": AdvData(96541, "Wild East"),
    "Wild East: Dunes Gunsmith 2": AdvData(96542, "Wild East"),
    "Wild East: Dunes Gunsmith 3": AdvData(96543, "Wild East"),
    "Wild East: Wild Revolver": AdvData(96544, "Wild East"),
    "Wild East: Nice Hat": AdvData(96545, "Wild East"),
    "Wild East: Broken Necklace": AdvData(96546, "Wild East"),
    "Dunes East: Golden Cactus": AdvData(96547, "Dunes East"),
    "Wild East: Genocide Friendliness Pellets": AdvData(96548, "Wild East"),
    "Steamworks: Washing Machine Beef Jerky": AdvData(96549, "Steamworks Entrance"),
    "Steamworks: Golden Bandana": AdvData(96550, "Steamworks Entrance"),
    "Steamworks: Lake Trash Can Gold": AdvData(96823, "Steamworks Entrance"),
    "Steamworks: Mo Steamworks 1": AdvData(96551, "Steamworks Entrance"),
    "Steamworks: Mo Steamworks 2": AdvData(96552, "Steamworks Entrance"),
    "Steamworks: Mo Steamworks 3": AdvData(96553, "Steamworks Entrance"),
    "Steamworks: Mo Robbery": AdvData(96825, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 1": AdvData(96554, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 2": AdvData(96555, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 3": AdvData(96556, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 4": AdvData(96557, "Steamworks Entrance"),
    "Steamworks: Box of Nails": AdvData(96558, "Steamworks Entrance"),
    "Steamworks: Box of Fries": AdvData(96559, "Steamworks Entrance"),
    "Steamworks: Box of Granola": AdvData(96560, "Steamworks Entrance"),
    "Steamworks Pacifist: Trash Can Beef Jerky": AdvData(96561, "Steamworks Pacifist"),
    "Steamworks Pacifist: Dark Room Gold Cache": AdvData(96642, "Steamworks Pacifist"),
    "Steamworks Exit: Broken Vending Machine": AdvData(96562, "Steamworks Axis"),
    "Steamworks Neutral: Closet Water": AdvData(96563, "Steamworks Neutral"),
    "Steamworks Neutral: Cake": AdvData(96564, "Steamworks Neutral"),
    "Steamworks Neutral: Hydrochloric Acid": AdvData(96565, "Steamworks Neutral"),
    "Steamworks Exit: Neutral Friendliness Pellets": AdvData(96566, "Steamworks Axis"),
    "Ketsukane Manor: Ceroba's Fridge": AdvData(96567, "Ketsukane Manor"),
    "Ketsukane Manor: Hidden Tape": AdvData(96568, "Ketsukane Manor"),
    "Hotland: Bits & Bytes Shop 1": AdvData(96569, "Hotland"),
    "Hotland: Bits & Bytes Shop 2": AdvData(96570, "Hotland"),
    "Hotland: Bits & Bytes Shop 3": AdvData(96571, "Hotland"),
    "Hotland: Bits & Bytes Shop 4": AdvData(96572, "Hotland"),
    "Hotland: Trash Can Hot Dog": AdvData(96573, "Hotland"),
    "Hotland: Trash Can Monster Candy": AdvData(96574, "Hotland"),
    "New Home: Bench Chisps": AdvData(96575, "New Home"),
    "New Home: Trash Can Soda": AdvData(96576, "New Home"),
    "LOVE 2": AdvData(96577, "???"),
    "LOVE 3": AdvData(96578, "???"),
    "LOVE 4": AdvData(96579, "???"),
    "LOVE 5": AdvData(96580, "???"),
    "LOVE 6": AdvData(96581, "???"),
    "LOVE 7": AdvData(96582, "???"),
    "LOVE 8": AdvData(96583, "???"),
    "LOVE 9": AdvData(96584, "???"),
    "LOVE 10": AdvData(96585, "???"),
    "LOVE 11": AdvData(96586, "???"),
    "LOVE 12": AdvData(96587, "???"),
    "LOVE 13": AdvData(96588, "???"),
    "LOVE 14": AdvData(96589, "???"),
    "LOVE 15": AdvData(96590, "???"),
    "LOVE 16": AdvData(96591, "???"),
    "LOVE 17": AdvData(96592, "???"),
    "LOVE 18": AdvData(96593, "???"),
    "LOVE 19": AdvData(96594, "???"),
    "LOVE 20": AdvData(96595, "???"),
    "ATK 2": AdvData(96596, "???"),
    "ATK 3": AdvData(96597, "???"),
    "ATK 4": AdvData(96598, "???"),
    "ATK 5": AdvData(96599, "???"),
    "ATK 6": AdvData(96600, "???"),
    "ATK 7": AdvData(96601, "???"),
    "ATK 8": AdvData(96602, "???"),
    "ATK 9": AdvData(96603, "???"),
    "ATK 10": AdvData(96604, "???"),
    "ATK 11": AdvData(96605, "???"),
    "ATK 12": AdvData(96606, "???"),
    "ATK 13": AdvData(96607, "???"),
    "ATK 14": AdvData(96608, "???"),
    "ATK 15": AdvData(96609, "???"),
    "ATK 16": AdvData(96610, "???"),
    "ATK 17": AdvData(96611, "???"),
    "ATK 18": AdvData(96612, "???"),
    "ATK 19": AdvData(96613, "???"),
    "ATK 20": AdvData(96614, "???"),
    "HP 2": AdvData(96615, "???"),
    "HP 3": AdvData(96616, "???"),
    "HP 4": AdvData(96617, "???"),
    "HP 5": AdvData(96618, "???"),
    "HP 6": AdvData(96619, "???"),
    "HP 7": AdvData(96620, "???"),
    "HP 8": AdvData(96621, "???"),
    "HP 9": AdvData(96622, "???"),
    "HP 10": AdvData(96623, "???"),
    "HP 11": AdvData(96624, "???"),
    "HP 12": AdvData(96625, "???"),
    "HP 13": AdvData(96626, "???"),
    "HP 14": AdvData(96627, "???"),
    "HP 15": AdvData(96628, "???"),
    "HP 16": AdvData(96629, "???"),
    "HP 17": AdvData(96630, "???"),
    "HP 18": AdvData(96631, "???"),
    "HP 19": AdvData(96632, "???"),
    "HP 20": AdvData(96633, "???"),
    "DEF 5": AdvData(96634, "???"),
    "DEF 9": AdvData(96635, "???"),
    "DEF 13": AdvData(96636, "???"),
    "DEF 17": AdvData(96637, "???"),
    "Decibat Victory": AdvData(96643, "Ruins"),
    "Dalv Victory": AdvData(96644, "Ruins"),
    "Martlet Pacifist/Neutral Victory": AdvData(96645, "Snowdin"),
    "Martlet Genocide Victory": AdvData(96646, "Snowdin"),
    "El Balidor Pacifist/Neutral Victory": AdvData(96647, "Dunes East"),
    "El Balidor Genocide Victory": AdvData(96648, "Dunes East"),
    "Starlo Victory": AdvData(96649, "Wild East"),
    "Ceroba Genocide Victory": AdvData(96650, "Wild East"),
    "Guardener Victory": AdvData(96651, "Steamworks Entrance"),
    "Axis Pacifist/Neutral Victory": AdvData(96652, "Steamworks Axis"),
    "Axis Genocide Victory": AdvData(96653, "Steamworks Axis"),
    "Mew Mew Love Blaster: 250 Points": AdvData(96655, "Dunes East"),
    "Mew Mew Love Blaster: 500 Points": AdvData(96656, "Dunes East"),
    "Mew Mew Love Blaster: 750 Points": AdvData(96657, "Dunes East"),
    "Mew Mew Love Blaster: 1000 Points": AdvData(96658, "Dunes East"),
    "Mew Mew Love Blaster: Clear": AdvData(96659, "Dunes East"),
    "Six Shooter: Clear": AdvData(96660, "Wild East"),
    "Six Shooter: Silver Rank Clear": AdvData(96661, "Wild East"),
    "Six Shooter: Gold Rank Clear": AdvData(96662, "Wild East"),
    "Ruins Spare 1": AdvData(96663, "Ruins"),
    "Ruins Spare 2": AdvData(96664, "Ruins"),
    "Ruins Spare 3": AdvData(96665, "Ruins"),
    "Ruins Spare 4": AdvData(96666, "Ruins"),
    "Ruins Spare 5": AdvData(96667, "Ruins"),
    "Ruins Spare 6": AdvData(96668, "Ruins"),
    "Ruins Spare 7": AdvData(96669, "Ruins"),
    "Ruins Spare 8": AdvData(96670, "Ruins"),
    "Ruins Spare 9": AdvData(96671, "Ruins"),
    "Ruins Spare 10": AdvData(96672, "Ruins"),
    "Ruins Spare 11": AdvData(96673, "Ruins"),
    "Ruins Spare 12": AdvData(96674, "Ruins"),
    "Ruins Spare 13": AdvData(96675, "Ruins"),
    "Ruins Spare 14": AdvData(96676, "Ruins"),
    "Ruins Spare 15": AdvData(96677, "Ruins"),
    "Ruins Spare 16": AdvData(96678, "Ruins"),
    "Ruins Spare 17": AdvData(96679, "Ruins"),
    "Ruins Spare 18": AdvData(96680, "Ruins"),
    "Ruins Spare 19": AdvData(96681, "Ruins"),
    "Ruins Spare 20": AdvData(96682, "Ruins"),
    "Ruins Kill 1": AdvData(96683, "Ruins"),
    "Ruins Kill 2": AdvData(96684, "Ruins"),
    "Ruins Kill 3": AdvData(96685, "Ruins"),
    "Ruins Kill 4": AdvData(96686, "Ruins"),
    "Ruins Kill 5": AdvData(96687, "Ruins"),
    "Ruins Kill 6": AdvData(96688, "Ruins"),
    "Ruins Kill 7": AdvData(96689, "Ruins"),
    "Ruins Kill 8": AdvData(96690, "Ruins"),
    "Ruins Kill 9": AdvData(96691, "Ruins"),
    "Ruins Kill 10": AdvData(96692, "Ruins"),
    "Ruins Kill 11": AdvData(96693, "Ruins"),
    "Ruins Kill 12": AdvData(96694, "Ruins"),
    "Ruins Kill 13": AdvData(96695, "Ruins"),
    "Ruins Kill 14": AdvData(96696, "Ruins"),
    "Ruins Kill 15": AdvData(96697, "Ruins"),
    "Ruins Kill 16": AdvData(96698, "Ruins"),
    "Ruins Kill 17": AdvData(96699, "Ruins"),
    "Ruins Kill 18": AdvData(96700, "Ruins"),
    "Ruins Kill 19": AdvData(96701, "Ruins"),
    "Ruins Kill 20": AdvData(96702, "Ruins"),
    "Snowdin Spare 1": AdvData(96703, "Snowdin"),
    "Snowdin Spare 2": AdvData(96704, "Snowdin"),
    "Snowdin Spare 3": AdvData(96705, "Snowdin"),
    "Snowdin Spare 4": AdvData(96706, "Snowdin"),
    "Snowdin Spare 5": AdvData(96707, "Snowdin"),
    "Snowdin Spare 6": AdvData(96708, "Snowdin"),
    "Snowdin Spare 7": AdvData(96709, "Snowdin"),
    "Snowdin Spare 8": AdvData(96710, "Snowdin"),
    "Snowdin Spare 9": AdvData(96711, "Snowdin"),
    "Snowdin Spare 10": AdvData(96712, "Snowdin"),
    "Snowdin Spare 11": AdvData(96713, "Snowdin"),
    "Snowdin Spare 12": AdvData(96714, "Snowdin"),
    "Snowdin Spare 13": AdvData(96715, "Snowdin"),
    "Snowdin Spare 14": AdvData(96716, "Snowdin"),
    "Snowdin Spare 15": AdvData(96717, "Snowdin"),
    "Snowdin Spare 16": AdvData(96718, "Snowdin"),
    "Snowdin Spare 17": AdvData(96719, "Snowdin"),
    "Snowdin Spare 18": AdvData(96720, "Snowdin"),
    "Snowdin Spare 19": AdvData(96721, "Snowdin"),
    "Snowdin Spare 20": AdvData(96722, "Snowdin"),
    "Snowdin Kill 1": AdvData(96723, "Snowdin"),
    "Snowdin Kill 2": AdvData(96724, "Snowdin"),
    "Snowdin Kill 3": AdvData(96725, "Snowdin"),
    "Snowdin Kill 4": AdvData(96726, "Snowdin"),
    "Snowdin Kill 5": AdvData(96727, "Snowdin"),
    "Snowdin Kill 6": AdvData(96728, "Snowdin"),
    "Snowdin Kill 7": AdvData(96729, "Snowdin"),
    "Snowdin Kill 8": AdvData(96730, "Snowdin"),
    "Snowdin Kill 9": AdvData(96731, "Snowdin"),
    "Snowdin Kill 10": AdvData(96732, "Snowdin"),
    "Snowdin Kill 11": AdvData(96733, "Snowdin"),
    "Snowdin Kill 12": AdvData(96734, "Snowdin"),
    "Snowdin Kill 13": AdvData(96735, "Snowdin"),
    "Snowdin Kill 14": AdvData(96736, "Snowdin"),
    "Snowdin Kill 15": AdvData(96737, "Snowdin"),
    "Snowdin Kill 16": AdvData(96738, "Snowdin"),
    "Snowdin Kill 17": AdvData(96739, "Snowdin"),
    "Snowdin Kill 18": AdvData(96740, "Snowdin"),
    "Snowdin Kill 19": AdvData(96741, "Snowdin"),
    "Snowdin Kill 20": AdvData(96742, "Snowdin"),
    "Dunes Spare 1": AdvData(96743, "Dunes West"),
    "Dunes Spare 2": AdvData(96744, "Dunes West"),
    "Dunes Spare 3": AdvData(96745, "Dunes West"),
    "Dunes Spare 4": AdvData(96746, "Dunes West"),
    "Dunes Spare 5": AdvData(96747, "Dunes West"),
    "Dunes Spare 6": AdvData(96748, "Dunes West"),
    "Dunes Spare 7": AdvData(96749, "Dunes West"),
    "Dunes Spare 8": AdvData(96750, "Dunes West"),
    "Dunes Spare 9": AdvData(96751, "Dunes West"),
    "Dunes Spare 10": AdvData(96752, "Dunes West"),
    "Dunes Spare 11": AdvData(96753, "Dunes West"),
    "Dunes Spare 12": AdvData(96754, "Dunes West"),
    "Dunes Spare 13": AdvData(96755, "Dunes West"),
    "Dunes Spare 14": AdvData(96756, "Dunes West"),
    "Dunes Spare 15": AdvData(96757, "Dunes West"),
    "Dunes Spare 16": AdvData(96758, "Dunes West"),
    "Dunes Spare 17": AdvData(96759, "Dunes West"),
    "Dunes Spare 18": AdvData(96760, "Dunes West"),
    "Dunes Spare 19": AdvData(96761, "Dunes West"),
    "Dunes Spare 20": AdvData(96762, "Dunes West"),
    "Dunes Kill 1": AdvData(96763, "Dunes West"),
    "Dunes Kill 2": AdvData(96764, "Dunes West"),
    "Dunes Kill 3": AdvData(96765, "Dunes West"),
    "Dunes Kill 4": AdvData(96766, "Dunes West"),
    "Dunes Kill 5": AdvData(96767, "Dunes West"),
    "Dunes Kill 6": AdvData(96768, "Dunes West"),
    "Dunes Kill 7": AdvData(96769, "Dunes West"),
    "Dunes Kill 8": AdvData(96770, "Dunes West"),
    "Dunes Kill 9": AdvData(96771, "Dunes West"),
    "Dunes Kill 10": AdvData(96772, "Dunes West"),
    "Dunes Kill 11": AdvData(96773, "Dunes West"),
    "Dunes Kill 12": AdvData(96774, "Dunes West"),
    "Dunes Kill 13": AdvData(96775, "Dunes West"),
    "Dunes Kill 14": AdvData(96776, "Dunes West"),
    "Dunes Kill 15": AdvData(96777, "Dunes West"),
    "Dunes Kill 16": AdvData(96778, "Dunes West"),
    "Dunes Kill 17": AdvData(96779, "Dunes West"),
    "Dunes Kill 18": AdvData(96780, "Dunes West"),
    "Dunes Kill 19": AdvData(96781, "Dunes West"),
    "Dunes Kill 20": AdvData(96782, "Dunes West"),
    "Steamworks Spare 1": AdvData(96783, "Steamworks Entrance"),
    "Steamworks Spare 2": AdvData(96784, "Steamworks Entrance"),
    "Steamworks Spare 3": AdvData(96785, "Steamworks Entrance"),
    "Steamworks Spare 4": AdvData(96786, "Steamworks Entrance"),
    "Steamworks Spare 5": AdvData(96787, "Steamworks Entrance"),
    "Steamworks Spare 6": AdvData(96788, "Steamworks Entrance"),
    "Steamworks Spare 7": AdvData(96789, "Steamworks Entrance"),
    "Steamworks Spare 8": AdvData(96790, "Steamworks Entrance"),
    "Steamworks Spare 9": AdvData(96791, "Steamworks Entrance"),
    "Steamworks Spare 10": AdvData(96792, "Steamworks Entrance"),
    "Steamworks Spare 11": AdvData(96793, "Steamworks Entrance"),
    "Steamworks Spare 12": AdvData(96794, "Steamworks Entrance"),
    "Steamworks Spare 13": AdvData(96795, "Steamworks Entrance"),
    "Steamworks Spare 14": AdvData(96796, "Steamworks Entrance"),
    "Steamworks Spare 15": AdvData(96797, "Steamworks Entrance"),
    "Steamworks Spare 16": AdvData(96798, "Steamworks Entrance"),
    "Steamworks Spare 17": AdvData(96799, "Steamworks Entrance"),
    "Steamworks Spare 18": AdvData(96800, "Steamworks Entrance"),
    "Steamworks Spare 19": AdvData(96801, "Steamworks Entrance"),
    "Steamworks Spare 20": AdvData(96802, "Steamworks Entrance"),
    "Steamworks Kill 1": AdvData(96803, "Steamworks Entrance"),
    "Steamworks Kill 2": AdvData(96804, "Steamworks Entrance"),
    "Steamworks Kill 3": AdvData(96805, "Steamworks Entrance"),
    "Steamworks Kill 4": AdvData(96806, "Steamworks Entrance"),
    "Steamworks Kill 5": AdvData(96807, "Steamworks Entrance"),
    "Steamworks Kill 6": AdvData(96808, "Steamworks Entrance"),
    "Steamworks Kill 7": AdvData(96809, "Steamworks Entrance"),
    "Steamworks Kill 8": AdvData(96810, "Steamworks Entrance"),
    "Steamworks Kill 9": AdvData(96811, "Steamworks Entrance"),
    "Steamworks Kill 10": AdvData(96812, "Steamworks Entrance"),
    "Steamworks Kill 11": AdvData(96813, "Steamworks Entrance"),
    "Steamworks Kill 12": AdvData(96814, "Steamworks Entrance"),
    "Steamworks Kill 13": AdvData(96815, "Steamworks Entrance"),
    "Steamworks Kill 14": AdvData(96816, "Steamworks Entrance"),
    "Steamworks Kill 15": AdvData(96817, "Steamworks Entrance"),
    "Steamworks Kill 16": AdvData(96818, "Steamworks Entrance"),
    "Steamworks Kill 17": AdvData(96819, "Steamworks Entrance"),
    "Steamworks Kill 18": AdvData(96820, "Steamworks Entrance"),
    "Steamworks Kill 19": AdvData(96821, "Steamworks Entrance"),
    "Steamworks Kill 20": AdvData(96822, "Steamworks Entrance"),

}

exclusion_table = {
    "pacifist": {
        "Dunes East: Cafe Dunes Geno Shop 1",
        "Dunes East: Cafe Dunes Geno Shop 2",
        "Dunes East: Cafe Dunes Geno Shop 3",
        "Dunes East: Cafe Dunes Geno Shop 4",
        "Wild East: Dunes Barkeep 2",
        "Wild East: Genocide Friendliness Pellets",
        "Steamworks: Mo Robbery",
        "Steamworks Neutral: Closet Water",
        "Steamworks Neutral: Cake",
        "Steamworks Neutral: Hydrochloric Acid",
        "Steamworks Exit: Neutral Friendliness Pellets",
        "LOVE 2",
        "LOVE 3",
        "LOVE 4",
        "LOVE 5",
        "LOVE 6",
        "LOVE 7",
        "LOVE 8",
        "LOVE 9",
        "LOVE 10",
        "LOVE 11",
        "LOVE 12",
        "LOVE 13",
        "LOVE 14",
        "LOVE 15",
        "LOVE 16",
        "LOVE 17",
        "LOVE 18",
        "LOVE 19",
        "LOVE 20",
        "ATK 2",
        "ATK 3",
        "ATK 4",
        "ATK 5",
        "ATK 6",
        "ATK 7",
        "ATK 8",
        "ATK 9",
        "ATK 10",
        "ATK 11",
        "ATK 12",
        "ATK 13",
        "ATK 14",
        "ATK 15",
        "ATK 16",
        "ATK 17",
        "ATK 18",
        "ATK 19",
        "ATK 20",
        "DEF 5",
        "DEF 9",
        "DEF 13",
        "DEF 17",
        "HP 2",
        "HP 3",
        "HP 4",
        "HP 5",
        "HP 6",
        "HP 7",
        "HP 8",
        "HP 9",
        "HP 10",
        "HP 11",
        "HP 12",
        "HP 13",
        "HP 14",
        "HP 15",
        "HP 16",
        "HP 17",
        "HP 18",
        "HP 19",
        "HP 20",
        "Martlet Genocide Victory",
        "El Balidor Genocide Victory",
        "Ceroba Genocide Victory",
        "Axis Genocide Victory",
    },
    "neutral": {
        "Dunes East: Cafe Dunes Geno Shop 1",
        "Dunes East: Cafe Dunes Geno Shop 2",
        "Dunes East: Cafe Dunes Geno Shop 3",
        "Dunes East: Cafe Dunes Geno Shop 4",
        "Wild East: Dunes Barkeep 2",
        "Wild East: Genocide Friendliness Pellets",
        "Steamworks: Mo Robbery",
        "Steamworks Pacifist: Trash Can Beef Jerky",
        "Steamworks Pacifist: Dark Room Gold Cache",
        "Ketsukane Manor: Ceroba's Fridge",
        "Ketsukane Manor: Hidden Tape",
        "New Home: Bench Chisps",
        "New Home: Trash Can Soda",
        "LOVE 2",
        "LOVE 3",
        "LOVE 4",
        "LOVE 5",
        "LOVE 6",
        "LOVE 7",
        "LOVE 8",
        "LOVE 9",
        "LOVE 10",
        "LOVE 11",
        "LOVE 12",
        "LOVE 13",
        "LOVE 14",
        "LOVE 15",
        "LOVE 16",
        "LOVE 17",
        "LOVE 18",
        "LOVE 19",
        "LOVE 20",
        "ATK 2",
        "ATK 3",
        "ATK 4",
        "ATK 5",
        "ATK 6",
        "ATK 7",
        "ATK 8",
        "ATK 9",
        "ATK 10",
        "ATK 11",
        "ATK 12",
        "ATK 13",
        "ATK 14",
        "ATK 15",
        "ATK 16",
        "ATK 17",
        "ATK 18",
        "ATK 19",
        "ATK 20",
        "DEF 5",
        "DEF 9",
        "DEF 13",
        "DEF 17",
        "HP 2",
        "HP 3",
        "HP 4",
        "HP 5",
        "HP 6",
        "HP 7",
        "HP 8",
        "HP 9",
        "HP 10",
        "HP 11",
        "HP 12",
        "HP 13",
        "HP 14",
        "HP 15",
        "HP 16",
        "HP 17",
        "HP 18",
        "HP 19",
        "HP 20",
        "Martlet Genocide Victory",
        "El Balidor Genocide Victory",
        "Ceroba Genocide Victory",
        "Axis Genocide Victory",
    },
    "genocide": {
        "Ruins: Dalv's Fridge",
        "Snowdin: Coffee Trade",
        "Snowdin: Mitten Trade",
        "Snowdin: Map Trade",
        "Snowdin: Matches Trade",
        "Snowdin: Scarf Trade",
        "Snowdin: Favorite Song Fan",
        "Dunes West: Trail Mix Chest",
        "Wild East: Nice Hat",
        "Wild East: Broken Necklace",
        "Steamworks Pacifist: Trash Can Beef Jerky",
        "Steamworks Pacifist: Dark Room Gold Cache",
        "Steamworks Exit: Neutral Friendliness Pellets",
        "Ketsukane Manor: Ceroba's Fridge",
        "Ketsukane Manor: Hidden Tape",
        "Steamworks Neutral: Cake",
        "Steamworks: Mo Steamworks 1",
        "Steamworks: Mo Steamworks 2",
        "Steamworks: Mo Steamworks 3",
        "Martlet Pacifist/Neutral Victory",
        "El Balidor Pacifist/Neutral Victory",
        "Starlo Victory",
        "Guardener Victory",
        "Axis Pacifist/Neutral Victory",
        "Mew Mew Love Blaster: 250 Points",
        "Mew Mew Love Blaster: 500 Points",
        "Mew Mew Love Blaster: 750 Points",
        "Mew Mew Love Blaster: 1000 Points",
        "Mew Mew Love Blaster: Clear",
        "Six Shooter: Clear",
        "Six Shooter: Silver Rank Clear",
        "Six Shooter: Gold Rank Clear",
    },
    "NoLove": {
        "LOVE 2",
        "LOVE 3",
        "LOVE 4",
        "LOVE 5",
        "LOVE 6",
        "LOVE 7",
        "LOVE 8",
        "LOVE 9",
        "LOVE 10",
        "LOVE 11",
        "LOVE 12",
        "LOVE 13",
        "LOVE 14",
        "LOVE 15",
        "LOVE 16",
        "LOVE 17",
        "LOVE 18",
        "LOVE 19",
        "LOVE 20",
    },
    "NoStats": {
        "ATK 2",
        "ATK 3",
        "ATK 4",
        "ATK 5",
        "ATK 6",
        "ATK 7",
        "ATK 8",
        "ATK 9",
        "ATK 10",
        "ATK 11",
        "ATK 12",
        "ATK 13",
        "ATK 14",
        "ATK 15",
        "ATK 16",
        "ATK 17",
        "ATK 18",
        "ATK 19",
        "ATK 20",
        "DEF 5",
        "DEF 9",
        "DEF 13",
        "DEF 17",
        "HP 2",
        "HP 3",
        "HP 4",
        "HP 5",
        "HP 6",
        "HP 7",
        "HP 8",
        "HP 9",
        "HP 10",
        "HP 11",
        "HP 12",
        "HP 13",
        "HP 14",
        "HP 15",
        "HP 16",
        "HP 17",
        "HP 18",
        "HP 19",
        "HP 20",
    },
    "all_routes": {
    },
    "NoMinigames": {
        "Mew Mew Love Blaster: 250 Points",
        "Mew Mew Love Blaster: 500 Points",
        "Mew Mew Love Blaster: 750 Points",
        "Mew Mew Love Blaster: 1000 Points",
        "Mew Mew Love Blaster: Clear",
        "Six Shooter: Clear",
        "Six Shooter: Silver Rank Clear",
        "Six Shooter: Gold Rank Clear",
    },
    "ReduceGrind": {
        "Ruins Spare 11",
        "Ruins Spare 12",
        "Ruins Spare 13",
        "Ruins Spare 14",
        "Ruins Spare 15",
        "Ruins Spare 16",
        "Ruins Spare 17",
        "Ruins Spare 18",
        "Ruins Spare 19",
        "Ruins Spare 20",
        "Ruins Kill 11",
        "Ruins Kill 12",
        "Ruins Kill 13",
        "Ruins Kill 14",
        "Ruins Kill 15",
        "Ruins Kill 16",
        "Ruins Kill 17",
        "Ruins Kill 18",
        "Ruins Kill 19",
        "Ruins Kill 20",
        "Snowdin Spare 11",
        "Snowdin Spare 12",
        "Snowdin Spare 13",
        "Snowdin Spare 14",
        "Snowdin Spare 15",
        "Snowdin Spare 16",
        "Snowdin Spare 17",
        "Snowdin Spare 18",
        "Snowdin Spare 19",
        "Snowdin Spare 20",
        "Snowdin Kill 11",
        "Snowdin Kill 12",
        "Snowdin Kill 13",
        "Snowdin Kill 14",
        "Snowdin Kill 15",
        "Snowdin Kill 16",
        "Snowdin Kill 17",
        "Snowdin Kill 18",
        "Snowdin Kill 19",
        "Snowdin Kill 20",
        "Dunes Spare 11",
        "Dunes Spare 12",
        "Dunes Spare 13",
        "Dunes Spare 14",
        "Dunes Spare 15",
        "Dunes Spare 16",
        "Dunes Spare 17",
        "Dunes Spare 18",
        "Dunes Spare 19",
        "Dunes Spare 20",
        "Dunes Kill 11",
        "Dunes Kill 12",
        "Dunes Kill 13",
        "Dunes Kill 14",
        "Dunes Kill 15",
        "Dunes Kill 16",
        "Dunes Kill 17",
        "Dunes Kill 18",
        "Dunes Kill 19",
        "Dunes Kill 20",
        "Steamworks Spare 11",
        "Steamworks Spare 12",
        "Steamworks Spare 13",
        "Steamworks Spare 14",
        "Steamworks Spare 15",
        "Steamworks Spare 16",
        "Steamworks Spare 17",
        "Steamworks Spare 18",
        "Steamworks Spare 19",
        "Steamworks Spare 20",
        "Steamworks Kill 11",
        "Steamworks Kill 12",
        "Steamworks Kill 13",
        "Steamworks Kill 14",
        "Steamworks Kill 15",
        "Steamworks Kill 16",
        "Steamworks Kill 17",
        "Steamworks Kill 18",
        "Steamworks Kill 19",
        "Steamworks Kill 20",
    },
    "NoSpareSanity": {
        "Ruins Spare 1",
        "Ruins Spare 2",
        "Ruins Spare 3",
        "Ruins Spare 4",
        "Ruins Spare 5",
        "Ruins Spare 6",
        "Ruins Spare 7",
        "Ruins Spare 8",
        "Ruins Spare 9",
        "Ruins Spare 10",
        "Ruins Spare 11",
        "Ruins Spare 12",
        "Ruins Spare 13",
        "Ruins Spare 14",
        "Ruins Spare 15",
        "Ruins Spare 16",
        "Ruins Spare 17",
        "Ruins Spare 18",
        "Ruins Spare 19",
        "Ruins Spare 20",
        "Snowdin Spare 1",
        "Snowdin Spare 2",
        "Snowdin Spare 3",
        "Snowdin Spare 4",
        "Snowdin Spare 5",
        "Snowdin Spare 6",
        "Snowdin Spare 7",
        "Snowdin Spare 8",
        "Snowdin Spare 9",
        "Snowdin Spare 10",
        "Snowdin Spare 11",
        "Snowdin Spare 12",
        "Snowdin Spare 13",
        "Snowdin Spare 14",
        "Snowdin Spare 15",
        "Snowdin Spare 16",
        "Snowdin Spare 17",
        "Snowdin Spare 18",
        "Snowdin Spare 19",
        "Snowdin Spare 20",
        "Dunes Spare 1",
        "Dunes Spare 2",
        "Dunes Spare 3",
        "Dunes Spare 4",
        "Dunes Spare 5",
        "Dunes Spare 6",
        "Dunes Spare 7",
        "Dunes Spare 8",
        "Dunes Spare 9",
        "Dunes Spare 10",
        "Dunes Spare 11",
        "Dunes Spare 12",
        "Dunes Spare 13",
        "Dunes Spare 14",
        "Dunes Spare 15",
        "Dunes Spare 16",
        "Dunes Spare 17",
        "Dunes Spare 18",
        "Dunes Spare 19",
        "Dunes Spare 20",
        "Steamworks Spare 1",
        "Steamworks Spare 2",
        "Steamworks Spare 3",
        "Steamworks Spare 4",
        "Steamworks Spare 5",
        "Steamworks Spare 6",
        "Steamworks Spare 7",
        "Steamworks Spare 8",
        "Steamworks Spare 9",
        "Steamworks Spare 10",
        "Steamworks Spare 11",
        "Steamworks Spare 12",
        "Steamworks Spare 13",
        "Steamworks Spare 14",
        "Steamworks Spare 15",
        "Steamworks Spare 16",
        "Steamworks Spare 17",
        "Steamworks Spare 18",
        "Steamworks Spare 19",
        "Steamworks Spare 20",
    },
    "NoKillSanity": {
        "Ruins Kill 1",
        "Ruins Kill 2",
        "Ruins Kill 3",
        "Ruins Kill 4",
        "Ruins Kill 5",
        "Ruins Kill 6",
        "Ruins Kill 7",
        "Ruins Kill 8",
        "Ruins Kill 9",
        "Ruins Kill 10",
        "Ruins Kill 11",
        "Ruins Kill 12",
        "Ruins Kill 13",
        "Ruins Kill 14",
        "Ruins Kill 15",
        "Ruins Kill 16",
        "Ruins Kill 17",
        "Ruins Kill 18",
        "Ruins Kill 19",
        "Ruins Kill 20",
        "Snowdin Kill 1",
        "Snowdin Kill 2",
        "Snowdin Kill 3",
        "Snowdin Kill 4",
        "Snowdin Kill 5",
        "Snowdin Kill 6",
        "Snowdin Kill 7",
        "Snowdin Kill 8",
        "Snowdin Kill 9",
        "Snowdin Kill 10",
        "Snowdin Kill 11",
        "Snowdin Kill 12",
        "Snowdin Kill 13",
        "Snowdin Kill 14",
        "Snowdin Kill 15",
        "Snowdin Kill 16",
        "Snowdin Kill 17",
        "Snowdin Kill 18",
        "Snowdin Kill 19",
        "Snowdin Kill 20",
        "Dunes Kill 1",
        "Dunes Kill 2",
        "Dunes Kill 3",
        "Dunes Kill 4",
        "Dunes Kill 5",
        "Dunes Kill 6",
        "Dunes Kill 7",
        "Dunes Kill 8",
        "Dunes Kill 9",
        "Dunes Kill 10",
        "Dunes Kill 11",
        "Dunes Kill 12",
        "Dunes Kill 13",
        "Dunes Kill 14",
        "Dunes Kill 15",
        "Dunes Kill 16",
        "Dunes Kill 17",
        "Dunes Kill 18",
        "Dunes Kill 19",
        "Dunes Kill 20",
        "Steamworks Kill 1",
        "Steamworks Kill 2",
        "Steamworks Kill 3",
        "Steamworks Kill 4",
        "Steamworks Kill 5",
        "Steamworks Kill 6",
        "Steamworks Kill 7",
        "Steamworks Kill 8",
        "Steamworks Kill 9",
        "Steamworks Kill 10",
        "Steamworks Kill 11",
        "Steamworks Kill 12",
        "Steamworks Kill 13",
        "Steamworks Kill 14",
        "Steamworks Kill 15",
        "Steamworks Kill 16",
        "Steamworks Kill 17",
        "Steamworks Kill 18",
        "Steamworks Kill 19",
        "Steamworks Kill 20",
    }
}
