from BaseClasses import Location
import typing


class AdvData(typing.NamedTuple):
    id: typing.Optional[int]
    region: str


class UndertaleYellowAdvancement(Location):
    game: str = "Undertale Yellow"

advancement_table = {
    "Ruins: Lemonade Stand": AdvData(96500, "Ruins"),
    "Ruins: Candy Corn": AdvData(96501, "Ruins"),
    "Ruins: Pebble Pile": AdvData(96502, "Ruins"),
    "Ruins: Stray Feather": AdvData(96503, "Ruins"),
    "Ruins: Corn Dog": AdvData(96504, "Ruins"),
    "Ruins: Golden Pear": AdvData(96505, "Ruins"),
    "Ruins: Dalv's Fridge": AdvData(96506, "Ruins"),
    "Snowdin: Ice Pellets": AdvData(96507, "Snowdin"),
    "Snowdin: Mo Snowdin 1": AdvData(96508, "Snowdin"),
    "Snowdin: Mo Snowdin 2": AdvData(96509, "Snowdin"),
    "Snowdin: Mo Snowdin 3": AdvData(96510, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 1": AdvData(96511, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 2": AdvData(96512, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 3": AdvData(96513, "Snowdin"),
    "Snowdin: Honeydew Inn Shop 4": AdvData(96514, "Snowdin"),
    "Snowdin: Favorite Song Fan": AdvData(96515, "Snowdin"),
    "Snowdin: Golden Coffee": AdvData(96516, "Snowdin"),
    "Snowdin: Coffee Trade": AdvData(96517, "Snowdin"),
    "Snowdin: Mitten Trade": AdvData(96518, "Snowdin"),
    "Snowdin: Map Trade": AdvData(96519, "Snowdin"),
    "Snowdin: Matches Trade": AdvData(96520, "Snowdin"),
    "Snowdin: Scarf Trade": AdvData(96521, "Snowdin"),
    "Snowdin: Coffee Bean Barrel": AdvData(96522, "Snowdin"),
    "Snowdin: Bench Pancakes": AdvData(96523, "Snowdin"),
    "Dunes West: Trail Mix Chest": AdvData(96524, "Dunes West"),
    "Dunes West: Packing Peanuts": AdvData(96525, "Dunes West"),
    "Dunes West: Mo Dunes 1": AdvData(96526, "Dunes West"),
    "Dunes West: Mo Dunes 2": AdvData(96527, "Dunes West"),
    "Dunes West: Mo Dunes 3": AdvData(96528, "Dunes West"),
    "Dunes West: Flint Pile": AdvData(96529, "Dunes West"),
    "Dunes West: Steel Buckle Cubby": AdvData(96530, "Dunes West"),
    "Dunes West: Pickaxe": AdvData(96531, "Dunes West"),
    "Dunes East: Safety Jacket Hanger": AdvData(96532, "Dunes East"),
    "Dunes East: Stale Fruitcake": AdvData(96533, "Dunes East"),
    "Dunes East: Gift Shop Mug": AdvData(96534, "Dunes East"),
    "Dunes East: Spider Bake Sale": AdvData(96535, "Dunes East"),
    "Dunes East: Pants Pocket Robbery": AdvData(96536, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 1": AdvData(96638, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 2": AdvData(96639, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 3": AdvData(96640, "Dunes East"),
    "Dunes East: Cafe Dunes Geno Shop 4": AdvData(96641, "Dunes East"),
    "Wild East: Wild East Barrel": AdvData(96654, "Wild East"),
    "Wild East: Dunes Barkeep 1": AdvData(96537, "Wild East"),
    "Wild East: Dunes Barkeep 2": AdvData(96538, "Wild East"),
    "Wild East: Dunes Barkeep 3": AdvData(96539, "Wild East"),
    "Wild East: Dunes Barkeep 4": AdvData(96540, "Wild East"),
    "Wild East: Dunes Gunsmith 1": AdvData(96541, "Wild East"),
    "Wild East: Dunes Gunsmith 2": AdvData(96542, "Wild East"),
    "Wild East: Dunes Gunsmith 3": AdvData(96543, "Wild East"),
    "Wild East: Wild Revolver": AdvData(96544, "Wild East"),
    "Wild East: Nice Hat": AdvData(96545, "Wild East"),
    "Wild East: Broken Necklace": AdvData(96546, "Wild East"),
    "Dunes East: Golden Cactus": AdvData(96547, "Dunes East"),
    "Wild East: Genocide Friendliness Pellets": AdvData(96548, "Wild East"),
    "Steamworks: Washing Machine Beef Jerky": AdvData(96549, "Steamworks Entrance"),
    "Steamworks: Golden Bandana": AdvData(96550, "Steamworks Entrance"),
    "Steamworks: Mo Steamworks 1": AdvData(96551, "Steamworks Entrance"),
    "Steamworks: Mo Steamworks 2": AdvData(96552, "Steamworks Entrance"),
    "Steamworks: Mo Steamworks 3": AdvData(96553, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 1": AdvData(96554, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 2": AdvData(96555, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 3": AdvData(96556, "Steamworks Entrance"),
    "Steamworks: Vendy Shop 4": AdvData(96557, "Steamworks Entrance"),
    "Steamworks: Box of Nails": AdvData(96558, "Steamworks Entrance"),
    "Steamworks: Box of Fries": AdvData(96559, "Steamworks Entrance"),
    "Steamworks: Box of Granola": AdvData(96560, "Steamworks Entrance"),
    "Steamworks Pacifist: Trash Can Beef Jerky": AdvData(96561, "Steamworks Pacifist"),
    "Steamworks Pacifist: Dark Room Gold Cache": AdvData(96642, "Steamworks Pacifist"),
    "Steamworks Exit: Broken Vending Machine": AdvData(96562, "Steamworks Axis"),
    "Steamworks Neutral: Closet Water": AdvData(96563, "Steamworks Neutral"),
    "Steamworks Neutral: Cake": AdvData(96564, "Steamworks Neutral"),
    "Steamworks Neutral: Hydrochloric Acid": AdvData(96565, "Steamworks Neutral"),
    "Steamworks Exit: Neutral Friendliness Pellets": AdvData(96566, "Steamworks Axis"),
    "Ketsukane Manor: Ceroba's Fridge": AdvData(96567, "Ketsukane Manor"),
    "Ketsukane Manor: Hidden Tape": AdvData(96568, "Ketsukane Manor"),
    "Hotland: Bits & Bytes Shop 1": AdvData(96569, "Hotland"),
    "Hotland: Bits & Bytes Shop 2": AdvData(96570, "Hotland"),
    "Hotland: Bits & Bytes Shop 3": AdvData(96571, "Hotland"),
    "Hotland: Bits & Bytes Shop 4": AdvData(96572, "Hotland"),
    "Hotland: Trash Can Hot Dog": AdvData(96573, "Hotland"),
    "Hotland: Trash Can Monster Candy": AdvData(96574, "Hotland"),
    "New Home: Bench Chisps": AdvData(96575, "New Home"),
    "New Home: Trash Can Soda": AdvData(96576, "New Home"),
    "LOVE 2": AdvData(96577, "???"),
    "LOVE 3": AdvData(96578, "???"),
    "LOVE 4": AdvData(96579, "???"),
    "LOVE 5": AdvData(96580, "???"),
    "LOVE 6": AdvData(96581, "???"),
    "LOVE 7": AdvData(96582, "???"),
    "LOVE 8": AdvData(96583, "???"),
    "LOVE 9": AdvData(96584, "???"),
    "LOVE 10": AdvData(96585, "???"),
    "LOVE 11": AdvData(96586, "???"),
    "LOVE 12": AdvData(96587, "???"),
    "LOVE 13": AdvData(96588, "???"),
    "LOVE 14": AdvData(96589, "???"),
    "LOVE 15": AdvData(96590, "???"),
    "LOVE 16": AdvData(96591, "???"),
    "LOVE 17": AdvData(96592, "???"),
    "LOVE 18": AdvData(96593, "???"),
    "LOVE 19": AdvData(96594, "???"),
    "LOVE 20": AdvData(96595, "???"),
    "ATK 2": AdvData(96596, "???"),
    "ATK 3": AdvData(96597, "???"),
    "ATK 4": AdvData(96598, "???"),
    "ATK 5": AdvData(96599, "???"),
    "ATK 6": AdvData(96600, "???"),
    "ATK 7": AdvData(96601, "???"),
    "ATK 8": AdvData(96602, "???"),
    "ATK 9": AdvData(96603, "???"),
    "ATK 10": AdvData(96604, "???"),
    "ATK 11": AdvData(96605, "???"),
    "ATK 12": AdvData(96606, "???"),
    "ATK 13": AdvData(96607, "???"),
    "ATK 14": AdvData(96608, "???"),
    "ATK 15": AdvData(96609, "???"),
    "ATK 16": AdvData(96610, "???"),
    "ATK 17": AdvData(96611, "???"),
    "ATK 18": AdvData(96612, "???"),
    "ATK 19": AdvData(96613, "???"),
    "ATK 20": AdvData(96614, "???"),
    "HP 2": AdvData(96615, "???"),
    "HP 3": AdvData(96616, "???"),
    "HP 4": AdvData(96617, "???"),
    "HP 5": AdvData(96618, "???"),
    "HP 6": AdvData(96619, "???"),
    "HP 7": AdvData(96620, "???"),
    "HP 8": AdvData(96621, "???"),
    "HP 9": AdvData(96622, "???"),
    "HP 10": AdvData(96623, "???"),
    "HP 11": AdvData(96624, "???"),
    "HP 12": AdvData(96625, "???"),
    "HP 13": AdvData(96626, "???"),
    "HP 14": AdvData(96627, "???"),
    "HP 15": AdvData(96628, "???"),
    "HP 16": AdvData(96629, "???"),
    "HP 17": AdvData(96630, "???"),
    "HP 18": AdvData(96631, "???"),
    "HP 19": AdvData(96632, "???"),
    "HP 20": AdvData(96633, "???"),
    "DEF 5": AdvData(96634, "???"),
    "DEF 9": AdvData(96635, "???"),
    "DEF 13": AdvData(96636, "???"),
    "DEF 17": AdvData(96637, "???"),
    "Decibat Victory": AdvData(96643, "Ruins"),
    "Dalv Victory": AdvData(96644, "Ruins"),
    "Martlet Pacifist/Neutral Victory": AdvData(96645, "Snowdin"),
    "Martlet Genocide Victory": AdvData(96646, "Snowdin"),
    "El Balidor Pacifist/Neutral Victory": AdvData(96647, "Dunes East"),
    "El Balidor Genocide Victory": AdvData(96648, "Dunes East"),
    "Starlo Victory": AdvData(96649, "Wild East"),
    "Ceroba Genocide Victory": AdvData(96650, "Wild East"),
    "Guardener Victory": AdvData(96651, "Steamworks Entrance"),
    "Axis Pacifist/Neutral Victory": AdvData(96652, "Steamworks Axis"),
    "Axis Genocide Victory": AdvData(96653, "Steamworks Axis"),
    "Mew Mew Love Blaster: 250 Points": AdvData(96655, "Dunes East"),
    "Mew Mew Love Blaster: 500 Points": AdvData(96656, "Dunes East"),
    "Mew Mew Love Blaster: 750 Points": AdvData(96657, "Dunes East"),
    "Mew Mew Love Blaster: 1000 Points": AdvData(96658, "Dunes East"),
    "Mew Mew Love Blaster: Clear": AdvData(96659, "Dunes East"),
    "Six Shooter: Clear": AdvData(96660, "Wild East"),
    "Six Shooter: Silver Rank Clear": AdvData(96661, "Wild East"),
    "Six Shooter: Gold Rank Clear": AdvData(96662, "Wild East"),
}

exclusion_table = {
    "pacifist": {
        "Dunes East: Cafe Dunes Geno Shop 1",
        "Dunes East: Cafe Dunes Geno Shop 2",
        "Dunes East: Cafe Dunes Geno Shop 3",
        "Dunes East: Cafe Dunes Geno Shop 4",
        "Wild East: Dunes Barkeep 2",
        "Wild East: Genocide Friendliness Pellets",
        "Steamworks Neutral: Closet Water",
        "Steamworks Neutral: Cake",
        "Steamworks Neutral: Hydrochloric Acid",
        "Steamworks Exit: Neutral Friendliness Pellets",
        "LOVE 2",
        "LOVE 3",
        "LOVE 4",
        "LOVE 5",
        "LOVE 6",
        "LOVE 7",
        "LOVE 8",
        "LOVE 9",
        "LOVE 10",
        "LOVE 11",
        "LOVE 12",
        "LOVE 13",
        "LOVE 14",
        "LOVE 15",
        "LOVE 16",
        "LOVE 17",
        "LOVE 18",
        "LOVE 19",
        "LOVE 20",
        "ATK 2",
        "ATK 3",
        "ATK 4",
        "ATK 5",
        "ATK 6",
        "ATK 7",
        "ATK 8",
        "ATK 9",
        "ATK 10",
        "ATK 11",
        "ATK 12",
        "ATK 13",
        "ATK 14",
        "ATK 15",
        "ATK 16",
        "ATK 17",
        "ATK 18",
        "ATK 19",
        "ATK 20",
        "DEF 5",
        "DEF 9",
        "DEF 13",
        "DEF 17",
        "HP 2",
        "HP 3",
        "HP 4",
        "HP 5",
        "HP 6",
        "HP 7",
        "HP 8",
        "HP 9",
        "HP 10",
        "HP 11",
        "HP 12",
        "HP 13",
        "HP 14",
        "HP 15",
        "HP 16",
        "HP 17",
        "HP 18",
        "HP 19",
        "HP 20",
        "Martlet Genocide Victory",
        "El Balidor Genocide Victory",
        "Ceroba Genocide Victory",
        "Axis Genocide Victory",
    },
    "neutral": {
        "Dunes East: Cafe Dunes Geno Shop 1",
        "Dunes East: Cafe Dunes Geno Shop 2",
        "Dunes East: Cafe Dunes Geno Shop 3",
        "Dunes East: Cafe Dunes Geno Shop 4",
        "Wild East: Dunes Barkeep 2",
        "Wild East: Genocide Friendliness Pellets",
        "Steamworks Pacifist: Trash Can Beef Jerky",
        "Steamworks Pacifist: Dark Room Gold Cache",
        "Ketsukane Manor: Ceroba's Fridge",
        "Ketsukane Manor: Hidden Tape",
        "New Home: Bench Chisps",
        "New Home: Trash Can Soda",
        "LOVE 2",
        "LOVE 3",
        "LOVE 4",
        "LOVE 5",
        "LOVE 6",
        "LOVE 7",
        "LOVE 8",
        "LOVE 9",
        "LOVE 10",
        "LOVE 11",
        "LOVE 12",
        "LOVE 13",
        "LOVE 14",
        "LOVE 15",
        "LOVE 16",
        "LOVE 17",
        "LOVE 18",
        "LOVE 19",
        "LOVE 20",
        "ATK 2",
        "ATK 3",
        "ATK 4",
        "ATK 5",
        "ATK 6",
        "ATK 7",
        "ATK 8",
        "ATK 9",
        "ATK 10",
        "ATK 11",
        "ATK 12",
        "ATK 13",
        "ATK 14",
        "ATK 15",
        "ATK 16",
        "ATK 17",
        "ATK 18",
        "ATK 19",
        "ATK 20",
        "DEF 5",
        "DEF 9",
        "DEF 13",
        "DEF 17",
        "HP 2",
        "HP 3",
        "HP 4",
        "HP 5",
        "HP 6",
        "HP 7",
        "HP 8",
        "HP 9",
        "HP 10",
        "HP 11",
        "HP 12",
        "HP 13",
        "HP 14",
        "HP 15",
        "HP 16",
        "HP 17",
        "HP 18",
        "HP 19",
        "HP 20",
        "Martlet Genocide Victory",
        "El Balidor Genocide Victory",
        "Ceroba Genocide Victory",
        "Axis Genocide Victory",
    },
    "genocide": {
        "Ruins: Dalv's Fridge",
        "Snowdin: Coffee Trade",
        "Snowdin: Mitten Trade",
        "Snowdin: Map Trade",
        "Snowdin: Matches Trade",
        "Snowdin: Scarf Trade",
        "Snowdin: Favorite Song Fan",
        "Dunes West: Trail Mix Chest",
        "Wild East: Nice Hat",
        "Wild East: Broken Necklace",
        "Steamworks Pacifist: Trash Can Beef Jerky",
        "Steamworks Pacifist: Dark Room Gold Cache",
        "Steamworks Exit: Neutral Friendliness Pellets",
        "Ketsukane Manor: Ceroba's Fridge",
        "Ketsukane Manor: Hidden Tape",
        "Steamworks Neutral: Cake",
        "Steamworks: Mo Steamworks 1",
        "Steamworks: Mo Steamworks 2",
        "Steamworks: Mo Steamworks 3",
        "Martlet Pacifist/Neutral Victory",
        "El Balidor Pacifist/Neutral Victory",
        "Starlo Victory",
        "Guardener Victory",
        "Axis Pacifist/Neutral Victory",
        "Mew Mew Love Blaster: 250 Points",
        "Mew Mew Love Blaster: 500 Points",
        "Mew Mew Love Blaster: 750 Points",
        "Mew Mew Love Blaster: 1000 Points",
        "Mew Mew Love Blaster: Clear",
        "Six Shooter: Clear",
        "Six Shooter: Silver Rank Clear",
        "Six Shooter: Gold Rank Clear",
    },
    "NoLove": {
        "LOVE 2",
        "LOVE 3",
        "LOVE 4",
        "LOVE 5",
        "LOVE 6",
        "LOVE 7",
        "LOVE 8",
        "LOVE 9",
        "LOVE 10",
        "LOVE 11",
        "LOVE 12",
        "LOVE 13",
        "LOVE 14",
        "LOVE 15",
        "LOVE 16",
        "LOVE 17",
        "LOVE 18",
        "LOVE 19",
        "LOVE 20",
    },
    "NoStats": {
        "ATK 2",
        "ATK 3",
        "ATK 4",
        "ATK 5",
        "ATK 6",
        "ATK 7",
        "ATK 8",
        "ATK 9",
        "ATK 10",
        "ATK 11",
        "ATK 12",
        "ATK 13",
        "ATK 14",
        "ATK 15",
        "ATK 16",
        "ATK 17",
        "ATK 18",
        "ATK 19",
        "ATK 20",
        "DEF 5",
        "DEF 9",
        "DEF 13",
        "DEF 17",
        "HP 2",
        "HP 3",
        "HP 4",
        "HP 5",
        "HP 6",
        "HP 7",
        "HP 8",
        "HP 9",
        "HP 10",
        "HP 11",
        "HP 12",
        "HP 13",
        "HP 14",
        "HP 15",
        "HP 16",
        "HP 17",
        "HP 18",
        "HP 19",
        "HP 20",
    },
    "all_routes": {
    },
    "NoMinigames": {
        "Mew Mew Love Blaster: 250 Points",
        "Mew Mew Love Blaster: 500 Points",
        "Mew Mew Love Blaster: 750 Points",
        "Mew Mew Love Blaster: 1000 Points",
        "Mew Mew Love Blaster: Clear",
        "Six Shooter: Clear",
        "Six Shooter: Silver Rank Clear",
        "Six Shooter: Gold Rank Clear",
    }
}
